language: node_js

node_js:
  - "0.10"
rvm:
  - "2.0.0"
gemfile:
  - Gemfile

before_install:
  - curl https://install.meteor.com | /bin/sh
  - npm install -g meteorite
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem install bundler
  - bundle install
services:
  - mongodb

script: "cucumber"

after_success: "mrt deploy freethinkingitchat.meteor.com"