language: node_js

node_js:
  - "0.10"
rvm:
  - "2.0.0"
gemfile:
  - Gemfile

before_install:
  - curl https://install.meteor.com | /bin/sh
  - npm install -g meteorite
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install bundler
  - bundle install
  - mrt update
services:
  - mongodb

script:
  - firefox
  - nohup bash -c "mrt &" && sleep 10
  - cucumber URL=localhost PORT=3000

after_success: "mrt deploy freethinkingitchat.meteor.com"